#!/bin/bash

LOGFILE="/var/log/update_script.log"
exec > >(sudo tee -a $LOGFILE) 2>&1

# Update package lists
sudo apt update

# Upgrade installed packages
sudo apt full-upgrade -y

# Remove unnecessary packages
sudo apt autoremove --purge -y

echo "System update and upgrade completed successfully."
